#!/usr/bin/env bash

number="${1}"
message=$(</dev/stdin)

SCRIPT_PATH=`dirname "${BASH_SOURCE[0]}"`

function mqttconf {
    grep -i "$1" $SCRIPT_PATH/mqtt2sms.ini | awk '{print $3}'
}

mosquitto_pub -h "$(mqttconf host)" -p "$(mqttconf port)" -u "$(mqttconf user)" -P "$(mqttconf password)" -t "sms" -m "{\"message\": \"$message\", \"number\": \"$number\"}"
